services:
  api:
    build: .
    image: evolve-common-api:local
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./storage:/app/storage
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: python -m uvicorn api.index:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 