"""add document node model

Revision ID: 70319cbe8799
Revises: 0733db020b53
Create Date: 2025-06-15 22:28:30.122042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70319cbe8799'
down_revision: Union[str, None] = '0733db020b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processed_document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('SECTION', 'HEADER', 'TABLE', 'IMAGE', 'TEXT', 'LIST', name='nodetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('node_metadata', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_document_id'], ['processed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_node_parent_id', 'document_nodes', ['parent_id'], unique=False)
    op.create_index('idx_document_node_processed_doc_position', 'document_nodes', ['processed_document_id', 'position'], unique=False)
    op.create_index('idx_document_node_processed_doc_type', 'document_nodes', ['processed_document_id', 'node_type'], unique=False)
    op.create_index(op.f('ix_document_nodes_id'), 'document_nodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_nodes_id'), table_name='document_nodes')
    op.drop_index('idx_document_node_processed_doc_type', table_name='document_nodes')
    op.drop_index('idx_document_node_processed_doc_position', table_name='document_nodes')
    op.drop_index('idx_document_node_parent_id', table_name='document_nodes')
    op.drop_table('document_nodes')
    # ### end Alembic commands ###
