"""add resources_path to processed_document

Revision ID: 9db4109bb4d4
Revises: fdca9cb69b06
Create Date: 2025-06-15 10:57:00.274576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db4109bb4d4'
down_revision: Union[str, None] = 'fdca9cb69b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_documents', sa.Column('resources_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_documents', 'resources_path')
    # ### end Alembic commands ###
